### ISSUE TITLE
Checking failure in Presburger

### ISSUE THREAD

**Issue by Armael** [umazalakain/fyp#1]
Hey,

I'm trying to build the proofs (I'm interested in particular in the formalization of the Omega Test), but it seems that there's an issue in Presburger:
```
/home/armael/research/uma-fyp/report/Presburger.lagda:469,5-502,8
Ambiguous name _≡⟨_⟩_. It could refer to any one of
  Presburger.≤-Reasoning._≡⟨_⟩_ bound at
    /usr/share/agda/lib/stdlib/Relation/Binary/Reasoning/Base/Triple.agda:108,1-7
  Presburger.≤-Reasoning._≈⟨_⟩_ bound at
    /usr/share/agda/lib/stdlib/Relation/Binary/Reasoning/Base/Triple.agda:100,1-7
```

Would you have any idea how to fix this? Unfortunately I don't really know any Agda myself…
(FWIW, I'm using agda version 2.6.0.1)

**Comment by umazalakain** [comment]
Hello! Yeah, this issue has to do with the Agda version the project was written for. I updated it to work with 2.6, which was surprisingly easy! Hope it works now ^^

Also, just a big red warning: this project is unfinished, there are postulates that still need to be proven. That said, and from what I remember, they shouldn't be especially difficult to prove, so if you feel like having a go please do!

**Comment by Armael** [comment]
Thanks a bunch, it works for me now. I'll keep you updated on my progress :) (it probably won't result in agda code though, as I'm trying to do something similar than you did but in Coq).
